name: Build and Deploy - Sandbox

on:
  push:
    branches: [sandbox]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy mule application to CloudHub environment Sandbox
        run: mvn -B deploy -DmuleDeploy -s .maven/settings.xml -Dshopify.username=$SHOPIFY_USERNAME -Dshopify.password=$SHOPIFY_PASSWORD -Dshopify.host=$SHOPIFY_HOST -Danypoint.mq.client_id=$ANYPOINT_MQ_CLIENT_ID -Danypoint.mq.client_secret=$ANYPOINT_MQ_CLIENT_SECRET
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
          PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
          BUSINESS_GROUP_ID: ${{ secrets.BUSINESS_GROUP_ID }}
          PLATFORM_CLIENT_ID: ${{ secrets.PLATFORM_CLIENT_ID }}
          PLATFORM_CLIENT_SECRET: ${{ secrets.PLATFORM_CLIENT_SECRET }}
          APP_NAME: sandbox-erp-to-shopify-scheduler-v1
          PLATFORM_ENV: Sandbox
          SHOPIFY_USERNAME: ${{ secrets.SHOPIFY_USERNAME }}
          SHOPIFY_PASSWORD:  ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_HOST: ${{ secrets.SHOPIFY_HOST }}
          ANYPOINT_MQ_CLIENT_ID: ${{ secrets.ANYPOINT_MQ_CLIENT_ID }}
          ANYPOINT_MQ_CLIENT_SECRET: ${{ secrets.ANYPOINT_MQ_CLIENT_SECRET }}
      - name: Publish test report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging